---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_facts:
      cloud: openstack
      region_name: regionOne
     register: result
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
     with_items: "{{result.ansible_facts.openstack_servers}}"
