- name: Configuration of Public and Private Networks
  os_network:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    name: "{{ item.value.network_name }}"
    external: "{{ item.value.external }}"
    admin_state_up: "{{ item.value.admin_state }}"
    provider_network_type: "{{ item.value.provider_network_type | default(omit) }}"
    provider_physical_network: "{{ item.value.provider_physical_network | default(omit) }}"
  with_dict: "{{ osp_networks }}"

- name: Configuration of Subnets for Public and Private SubNets
  os_subnet:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    network_name: "{{ item.value.network_name  }}"
    name: "{{ item.value.subnet_name  }}"
    cidr: "{{ item.value.cidr_network }}"
    ip_version: "{{ item.value.ip_version }}"
    gateway_ip: "{{ item.value.gateway_ip | default(omit) }}"
    enable_dhcp: "{{ item.value.enable_dhcp }}"
    allocation_pool_start: "{{ item.value.allocation_pool_start | default(omit) }}"
    allocation_pool_end: "{{ item.value.allocation_pool_end | default(omit) }}"
    dns_nameservers:
      - 8.8.8.8
      - 8.8.8.7
  with_dict: "{{ osp_networks }}"

- name: Create Router
  os_router:
    cloud: "{{ item.value.cloud_name }}"
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    network: "{{ item.value.network }}"
    external_fixed_ips:
      - { subnet: ext_subnet }
    interfaces:
      - "{{ item.value.interfaces }}"
  with_dict: "{{ osp_router }}"